export const IDS = {
    COMBAT_ID: 'combat',
    WITHERING_ATTACK_ID: 'withering-attacks',
    DECISIVE_ATTACK_ID: 'decisive-attacks',
    GAMBIT_ATTACK_ID: 'gambit-attacks',
    SPLIT_WITHERING_ATTACK_ID: 'split-withering-attacks',
    SPLIT_DECISIVE_ATTACK_ID: 'split-decisive-attacks',
    SPLIT_GAMBIT_ATTACK_ID: 'split-gambit-attacks',
    ACTION_ROLL_ID: 'action-rolls',
    SAVED_ROLL_ID: 'saved-rolls',
    ACTION_ID: 'actions',
    ABILITY_ID: 'abilities',
    ROLL_CHARM_ID: 'roll-charms',
    COMBAT_ACTION_ID: 'combat-actions',
    DEFENSIVE_CHARM_ID: 'defensive-charms',
    CHARM_ID: 'charms',
    SPECIFIC_ACTION_ID: 'specific-actions',
    CRAFT_ACTION_ID: 'craft-actions'
}

export const ACTION_TYPES = {
    WITHERING_ATTACK: 'withering_attack',
    DECISIVE_ATTACK: 'decisive_attack',
    GAMBIT_ATTACK: 'gambit_attack',
    SPLIT_WITHERING_ATTACK: 'split_withering_attack',
    SPLIT_DECISIVE_ATTACK: 'split_decisive_attack',
    SPLIT_GAMBIT_ATTACK: 'split_gambit_attack',
    CHARM: 'charm',
    ROLL_CHARM: 'roll_charm',
    DEFENSIVE_CHARM: 'defensive_charm',
    SAVED_ROLL: 'saved_roll',
    MARTIAL_ART: 'martial_art',
    CRAFT: 'craft',
    ABILITY_ROLL: 'ability_roll',
    CUSTOM_ABILITY_ROLL: 'custom_ability_roll',
    POOL_ROLL: 'pool_roll',
    ACTION_ROLL: 'action_roll',
    COMBAT_ACTION: 'combat_action',
    SPECIFIC_ACTION: 'specific_action',
    CRAFT_ACTION: 'craft_action'
}

export const GROUP = {
    actions: { id: 'actions', name: 'Ex3.Actions', type: 'system' },
    specific_actions: { id: 'specific-actions', name: 'Ex3.SpecificActions', type: 'system' },
    craft_actions: { id: 'craft-actions', name: 'Ex3.Crafts', type: 'system' },
    abilities: { id: 'abilities', name: 'Ex3.Abilities', type: 'system' },
    charms: { id: 'charms', name: 'Ex3.Charms', type: 'system' },
    roll_charms: { id: 'roll-charms', name: 'Ex3.RollCharms', type: 'system' },
    defensive_charms: { id: 'defensive-charms', name: 'Ex3.DefensiveCharms', type: 'system' },
    combat_actions:  { id: 'combat-actions', name: 'Ex3.Actions', type: 'system' },
    withering_attacks:  { id: 'withering-attacks', name: 'Ex3.WitheringAttacks', type: 'system' },
    decisive_attacks:  { id: 'decisive-attacks', name: 'Ex3.DecisiveAttacks', type: 'system' },
    gambit_attacks:  { id: 'gambit-attacks', name: 'Ex3.GambitAttacks', type: 'system' },
    split_withering_attacks:  { id: 'split-withering-attacks', name: 'Ex3.SplitWitheringAttacks', type: 'system' },
    split_decisive_attacks:  { id: 'split-decisive-attacks', name: 'Ex3.SplitDecisiveAttacks', type: 'system' },
    split_gambit_attacks:  { id: 'split-gambit-attacks', name: 'Ex3.SplitGambitAttacks', type: 'system' },
    saved_rolls: { id: 'saved-rolls', name: 'Ex3.SavedRolls', type: 'system' },
}